[package]
name = "NullOS"
version = "0.1.0"
edition = "2021"
exclude = ["Bootloader/*"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile = "0.2.6"
x86_64 = "0.14.2"